version: 2

formats: []

build:
  image: latest

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: setuptools
      path: .
    - requirements: requirements/docs.txt
    - requirements: requirements/procinfo.txt
    - requirements: requirements/voice.txt
